### ISSUE TITLE
 Create Address result difference

### ISSUE THREAD

**Issue by zhaosha19850618** [tronprotocol/tron-cli#6]
import requests,codecs
url = 'http://api.trongrid.io/wallet/createaddress'
#data = {'value':codecs.encode('icomefromchina','utf-8')}
data = {'value':'7465737470617373776f7264'}
res = requests.post(url,data)
print(res.status_code)
print(res.json())
**zhaosha@ubuntu:~$ python 1.py
200
{'base58checkAddress': 'TFxUNfCwhiTSnNntkcXvicSTf4otPXeCXL', 'value': '4141ad2bc63a2059f9b623533d87fe99887d794847'}**

_zhaosha@ubuntu:~$ curl -X POST https://api.trongrid.io/wallet/createaddress -d '{"value":"7465737470617373776f7264"}'
{"base58checkAddress":"TWwv3YcHJ1NfMemQSmXCPY48RR1tsY3n9N","value":"41e61c1205ee029fb4e41f294afd448cc5d578c8ef"}_

**Comment by serderovsh** [comment]
It is not recommended to create an account, through a request to the node. Is it dangerous.

**Comment by wxue** [comment]
It's recommended to create an account through wallets. (here's an example: https://developers.tron.network/docs/tronscan-wallet)

If you are still interested on the api plz check the doc here: https://developers.tron.network/v3.0/reference#walletcreateaddress

Close issue since this is not related to this repo.
